### PR TITLE
Fix exercise input crash bug

### LINKED ISSUE #100: [PE-D][Tester A] InputMissMatchException not handled properly
Crashes the program

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ThawTunZan/ped#4

### LINKED ISSUE #137: [PE-D][Tester D] game crash in command "exercise"
game crash when the input is not integer

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: classskipper351/ped#6

### PR DESCRIPTION
**Pull request by StargazerX0**
Fix exercise input crash bug #137

### CODE REVIEW

File: src/main/java/minigame/TicTacToe.java [hunk 1]
```diff
@@ -167,16 +168,22 @@ public void startGame() {
...
                 placeMark(row, column);
+
                 if (!isGameOver) {
                     ResponseManager.indentPrint("AI's turn!\n");
                     placeAIMark();
                     currentMark = playerMark;
                 }
+            } catch (InputMismatchException e) {
+                ResponseManager.indentPrint("Invalid input! Please enter integer only.\n");
+                scanner.nextLine(); // Clear the buffer by consuming the invalid input
```
Comment (ZMinghuiZ) [inline src/main/java/minigame/TicTacToe.java:186]: good exception handling to solve the problem

**Review by ZMinghuiZ — APPROVED** [review]
